import { useState } from 'react';
import { ArrowUpRight, BellRing, ClipboardList, FilePlus2, Mail, Plus, Search } from 'lucide-react';
import { MODULES, type Task, type Template, type WorkspaceView } from '../../domain/onboarding';
import { Block, TextField } from '../mf';
import { TaskBadge } from './FormSections';
import { deliveryLabels, formatDate, taskLabels } from './display';

export function WorkspaceList({ workspace, role, busy, onCreate, onOpen, onMail, onInvite, onRemind, onResend }: {
  workspace: WorkspaceView; role: 'hr' | 'employee'; busy: boolean; onCreate: () => void; onOpen: (task: Task) => void; onMail?: (task: Task) => void; onInvite: (template: Template) => void; onRemind: () => void; onResend: (task: Task) => void;
}) {
  const [filter, setFilter] = useState('all');
  const [search, setSearch] = useState('');
  const counts = { all: workspace.tasks.length, open: workspace.tasks.filter((task) => ['NOT_STARTED', 'IN_PROGRESS', 'RETURNED'].includes(task.status)).length, submitted: workspace.tasks.filter((task) => task.status === 'SUBMITTED').length, confirmed: workspace.tasks.filter((task) => task.status === 'CONFIRMED').length };
  const filtered = workspace.tasks.filter((task) => `${task.employeeName} ${task.email} ${task.template.title}`.toLowerCase().includes(search.toLowerCase()) && (filter === 'all' || filter === 'open' && ['NOT_STARTED', 'IN_PROGRESS', 'RETURNED'].includes(task.status) || filter === 'submitted' && task.status === 'SUBMITTED' || filter === 'confirmed' && task.status === 'CONFIRMED'));
  const hasMail = (task: Task) => workspace.outbox.some((message) => message.taskId === task.id);
  return <><div className="page-heading"><div><h1>入社手続き</h1><p>{role === 'hr' ? '新しい仲間を迎える準備を、ひとつの場所で。' : '入社に必要な情報を入力し、HR に提出してください。'}</p></div>{role === 'hr' && <div className="button-row"><button className="button secondary" onClick={onRemind} disabled={busy}><BellRing size={16} />リマインドを実行</button><button className="button primary" onClick={onCreate} disabled={busy}><Plus size={17} />ワークフローを作成</button></div>}</div>
    {role === 'hr' && <div className="overview-strip"><div><ClipboardList size={21} /><span>進行中の手続き<strong>{counts.open}<small>名</small></strong></span></div><div><Mail size={21} /><span>提出済み・確認待ち<strong>{counts.submitted}<small>名</small></strong></span></div><div><FilePlus2 size={21} /><span>確認完了<strong>{counts.confirmed}<small>名</small></strong></span></div></div>}
    <Block className="workspace-panel"><div className="panel-title"><h2>{role === 'hr' ? '従業員の進捗' : 'あなたの手続き'}</h2><span>{workspace.tasks.length} 件</span></div><div className="table-controls"><div className="filter-tabs" aria-label="状態で絞り込み">{([['all', 'すべて'], ['open', '未提出'], ['submitted', '提出済み'], ['confirmed', '確認済み']] as const).map(([key, label]) => <button key={key} className={filter === key ? 'active' : ''} aria-pressed={filter === key} onClick={() => setFilter(key)}>{label}<span>{counts[key]}</span></button>)}</div><div className="search-field"><Search size={16} /><TextField aria-label="従業員・手続きを検索" placeholder="名前・メールアドレスを検索" value={search} onChange={(e) => setSearch(e.target.value)} /></div></div>
      {filtered.length ? <div className="table-scroll"><table className="task-table"><thead><tr><th>{role === 'hr' ? '従業員' : '手続き'}</th>{role === 'hr' && <th>ワークフロー</th>}<th>提出期限</th><th>ステータス</th>{role === 'hr' && <th>模拟メール</th>}<th><span className="sr-only">操作</span></th></tr></thead><tbody>{filtered.map((task) => <tr key={task.id}><td><div className="person-cell"><span className="avatar">{task.employeeName.slice(0, 1)}</span><div><strong>{role === 'hr' ? task.employeeName : task.template.title}</strong><small>{task.email}</small></div></div></td>{role === 'hr' && <td><span className="table-template">{task.template.title}</span></td>}<td className="date-cell">{formatDate(task.template.dueDate)}</td><td><TaskBadge task={task} /></td>{role === 'hr' && <td><div className="delivery-cell"><span className={task.delivery === 'FAILED' ? 'field-error' : 'muted'}>{deliveryLabels[task.delivery]}</span>{onMail && hasMail(task) && <button className="text-button" onClick={() => onMail(task)} disabled={busy} aria-label={`${task.employeeName}の模拟メールを見る`}>メールを見る</button>}{['FAILED', 'PENDING'].includes(task.delivery) && <button className="text-button" disabled={busy} onClick={() => onResend(task)}>模拟メールを再記録</button>}</div></td>}<td><button className="text-button open-task" onClick={() => onOpen(task)} disabled={busy} aria-label={`${task.employeeName}の${task.template.title}を開く`}>{role === 'hr' || ['SUBMITTED', 'CONFIRMED'].includes(task.status) ? '詳細' : task.status === 'NOT_STARTED' ? '入力する' : '入力を再開'}<ArrowUpRight size={14} /></button></td></tr>)}</tbody></table></div> : <div className="empty-state"><ClipboardList size={32} /><h3>{workspace.tasks.length ? '条件に一致する手続きがありません' : '手続きはまだありません'}</h3><p>{workspace.tasks.length ? '検索条件やステータスを変更してください。' : role === 'hr' ? 'AI アシスタントに依頼するか、ワークフローを作成して従業員を招待しましょう。' : 'HR からの招待をお待ちください。'}</p></div>}</Block>
    {role === 'hr' && <section className="templates-section"><div className="panel-title"><div><h2>ワークフローテンプレート</h2><p>同じフォームを、次の新入社員にも。</p></div></div><div className="template-grid">{workspace.templates.map((template) => <Block className="template-card" key={template.id}><div className="template-icon"><ClipboardList size={23} /></div><h3>{template.title}</h3><p>{MODULES.filter((module) => template.modules.includes(module.id)).map((module) => module.label).join(' / ')}</p><div><span>{template.modules.length} セクション</span><button className="text-button" onClick={() => onInvite(template)} disabled={busy}><Plus size={15} />従業員を招待</button></div></Block>)}<button className="new-template" onClick={onCreate} disabled={busy}><Plus size={23} /><strong>テンプレートを作成</strong><span>必要な情報を自由に組み合わせる</span></button></div></section>}
  </>;
}

export function ActivityList({ workspace, onOpen }: { workspace: WorkspaceView; onOpen: (task: Task) => void }) {
  const events = workspace.tasks.flatMap((task) => task.history.map((event) => ({ task, event }))).sort((a, b) => b.event.at.localeCompare(a.event.at));
  return <><div className="page-heading"><div><h1>手続きの履歴</h1><p>招待から提出・確認までの記録を振り返ります。</p></div></div><Block className="workspace-panel">{events.length ? <ul className="activity-list">{events.map(({ task, event }) => <li key={`${task.id}-${event.id}`}><span className="avatar">{task.employeeName.slice(0, 1)}</span><div><button className="text-button" onClick={() => onOpen(task)}>{task.employeeName} · {task.template.title}</button><p>{({ INVITED: '招待を作成しました', DRAFT_SAVED: '一時保存しました', SUBMITTED: '提出しました', CONFIRMED: '確認しました', RETURNED: '修正を依頼しました', REMINDED: 'リマインドを送信しました', EMAIL_SIMULATED: '模拟メールを記録しました', EMAIL_FAILED: '模拟メールの記録に失敗しました' } as Record<string, string>)[event.type] ?? taskLabels[task.status]}</p>{event.note && <small>{event.note}</small>}</div><time>{formatDate(event.at)}</time></li>)}</ul> : <div className="empty-state">手続きが始まると、ここに履歴が表示されます。</div>}</Block></>;
}
